[2023-12-09T16:07:50.792+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:37:44.645209+00:00 [queued]>
[2023-12-09T16:07:50.796+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:37:44.645209+00:00 [queued]>
[2023-12-09T16:07:50.796+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T16:07:50.806+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-12-09 10:37:44.645209+00:00
[2023-12-09T16:07:50.810+0530] {standard_task_runner.py:57} INFO - Started process 18650 to run task
[2023-12-09T16:07:50.813+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'load', 'manual__2023-12-09T10:37:44.645209+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpfp1rm789']
[2023-12-09T16:07:50.814+0530] {standard_task_runner.py:85} INFO - Job 143: Subtask load
[2023-12-09T16:07:50.836+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:37:44.645209+00:00 [running]> on host Iris
[2023-12-09T16:07:50.882+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T10:37:44.645209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T10:37:44.645209+00:00'
[2023-12-09T16:07:50.899+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2023-12-09T16:07:50.904+0530] {logging_mixin.py:154} INFO - bala
[2023-12-09T16:07:50.904+0530] {logging_mixin.py:154} INFO - 

---------------------------<connection object at 0x7f0b38d86e00; dsn: 'user=postgres password=xxx dbname=postgres host=localhost port=5432', closed: 0> --------------------------------
[2023-12-09T16:07:50.904+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Load.py", line 39, in load_to_db
    for i in conn:
TypeError: 'psycopg2.extensions.connection' object is not iterable
[2023-12-09T16:07:50.908+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=load, execution_date=20231209T103744, start_date=20231209T103750, end_date=20231209T103750
[2023-12-09T16:07:50.918+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 143 for task load ('psycopg2.extensions.connection' object is not iterable; 18650)
[2023-12-09T16:07:50.945+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T16:07:50.952+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
