[2023-12-31T21:37:17.285+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2023-12-31T21:37:17.291+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2023-12-31T21:37:17.291+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-31T21:37:17.307+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): bash> on 2023-12-29 00:00:00+00:00
[2023-12-31T21:37:17.311+0530] {standard_task_runner.py:57} INFO - Started process 26156 to run task
[2023-12-31T21:37:17.314+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trigger', 'bash', 'scheduled__2023-12-29T00:00:00+00:00', '--job-id', '486', '--raw', '--subdir', 'DAGS_FOLDER/summa.py', '--cfg-path', '/tmp/tmpurj4o99w']
[2023-12-31T21:37:17.316+0530] {standard_task_runner.py:85} INFO - Job 486: Subtask bash
[2023-12-31T21:37:17.350+0530] {task_command.py:416} INFO - Running <TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [running]> on host Iris
[2023-12-31T21:37:17.405+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger' AIRFLOW_CTX_TASK_ID='bash' AIRFLOW_CTX_EXECUTION_DATE='2023-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-29T00:00:00+00:00'
[2023-12-31T21:37:17.406+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-31T21:37:17.406+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'execution_date =2023-12-29']
[2023-12-31T21:37:17.414+0530] {subprocess.py:86} INFO - Output:
[2023-12-31T21:37:17.414+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: execution_date: command not found
[2023-12-31T21:37:17.414+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-31T21:37:17.422+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-31T21:37:17.425+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=trigger, task_id=bash, execution_date=20231229T000000, start_date=20231231T160717, end_date=20231231T160717
[2023-12-31T21:37:17.437+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 486 for task bash (Bash command failed. The command returned a non-zero exit code 127.; 26156)
[2023-12-31T21:37:17.446+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-31T21:37:17.456+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-31T22:38:40.006+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2023-12-31T22:38:40.009+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [queued]>
[2023-12-31T22:38:40.009+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-31T22:38:40.020+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): bash> on 2023-12-29 00:00:00+00:00
[2023-12-31T22:38:40.022+0530] {standard_task_runner.py:57} INFO - Started process 49588 to run task
[2023-12-31T22:38:40.024+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'trigger', 'bash', 'scheduled__2023-12-29T00:00:00+00:00', '--job-id', '492', '--raw', '--subdir', 'DAGS_FOLDER/summa.py', '--cfg-path', '/tmp/tmp9cvoqd2d']
[2023-12-31T22:38:40.024+0530] {standard_task_runner.py:85} INFO - Job 492: Subtask bash
[2023-12-31T22:38:40.045+0530] {task_command.py:416} INFO - Running <TaskInstance: trigger.bash scheduled__2023-12-29T00:00:00+00:00 [running]> on host Iris
[2023-12-31T22:38:40.092+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger' AIRFLOW_CTX_TASK_ID='bash' AIRFLOW_CTX_EXECUTION_DATE='2023-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-29T00:00:00+00:00'
[2023-12-31T22:38:40.092+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-31T22:38:40.092+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '"echo" execution_date =2023-12-29 link = []\n                            run_id=scheduled__2023-12-29T00:00:00+00:00  ']
[2023-12-31T22:38:40.098+0530] {subprocess.py:86} INFO - Output:
[2023-12-31T22:38:40.098+0530] {subprocess.py:93} INFO - execution_date =2023-12-29 link = []
[2023-12-31T22:38:40.098+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-31T22:38:40.111+0530] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger, task_id=bash, execution_date=20231229T000000, start_date=20231231T170840, end_date=20231231T170840
[2023-12-31T22:38:40.156+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-31T22:38:40.172+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
