[2024-01-02T20:02:05.633+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_match_table manual__2024-01-02T14:31:40.399937+00:00 [queued]>
[2024-01-02T20:02:05.637+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.Create_match_table manual__2024-01-02T14:31:40.399937+00:00 [queued]>
[2024-01-02T20:02:05.637+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2024-01-02T20:02:05.647+0530] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): Create_match_table> on 2024-01-02 14:31:40.399937+00:00
[2024-01-02T20:02:05.649+0530] {standard_task_runner.py:57} INFO - Started process 45018 to run task
[2024-01-02T20:02:05.651+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'Create_match_table', 'manual__2024-01-02T14:31:40.399937+00:00', '--job-id', '629', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpyu5uh_6r']
[2024-01-02T20:02:05.652+0530] {standard_task_runner.py:85} INFO - Job 629: Subtask Create_match_table
[2024-01-02T20:02:05.672+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.Create_match_table manual__2024-01-02T14:31:40.399937+00:00 [running]> on host Iris
[2024-01-02T20:02:05.707+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='Create_match_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T14:31:40.399937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-02T14:31:40.399937+00:00'
[2024-01-02T20:02:05.707+0530] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS Match_data(
        
        "match_id" NUMERIC PRIMARY KEY,
        "match_no" TEXT,
        "date" TEXT,
        "series" TEXT,
        "season" TEXT, 
        "venue" TEXT, 
        "team_a" TEXT, 
        "team_b" TEXT,
        "team_a_11" TEXT, 
        "team_b_11" TEXT, 
        "team_a_subs" TEXT, 
        "team_b_subs" TEXT,
        "toss" TEXT,
        "toss_winner" TEXT,
        "toss_choosen" TEXT,
        "winner" TEXT, 
        "player_of_the_match" TEXT
        )
[2024-01-02T20:02:05.710+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T20:02:05.895+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2024-01-02T20:02:05.896+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-01-02T20:02:05.899+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=Create_match_table, execution_date=20240102T143140, start_date=20240102T143205, end_date=20240102T143205
[2024-01-02T20:02:05.909+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 629 for task Create_match_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 45018)
[2024-01-02T20:02:05.943+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T20:02:05.958+0530] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
