[2024-01-02T23:25:35.783+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summa1.copy_files_to_hadoop manual__2024-01-02T17:55:32.528955+00:00 [queued]>
[2024-01-02T23:25:35.789+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summa1.copy_files_to_hadoop manual__2024-01-02T17:55:32.528955+00:00 [queued]>
[2024-01-02T23:25:35.789+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-02T23:25:35.802+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): copy_files_to_hadoop> on 2024-01-02 17:55:32.528955+00:00
[2024-01-02T23:25:35.805+0530] {standard_task_runner.py:57} INFO - Started process 57701 to run task
[2024-01-02T23:25:35.807+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'summa1', 'copy_files_to_hadoop', 'manual__2024-01-02T17:55:32.528955+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/summa.py', '--cfg-path', '/tmp/tmprwz63j6q']
[2024-01-02T23:25:35.808+0530] {standard_task_runner.py:85} INFO - Job 653: Subtask copy_files_to_hadoop
[2024-01-02T23:25:35.840+0530] {task_command.py:416} INFO - Running <TaskInstance: summa1.copy_files_to_hadoop manual__2024-01-02T17:55:32.528955+00:00 [running]> on host Iris
[2024-01-02T23:25:35.866+0530] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'copy_files_to_hadoop', field 'bash_command'. Template: 'sh summa.sh'
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh summa.sh
[2024-01-02T23:25:35.867+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh summa.sh
[2024-01-02T23:25:35.869+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=summa1, task_id=copy_files_to_hadoop, execution_date=20240102T175532, start_date=20240102T175535, end_date=20240102T175535
[2024-01-02T23:25:35.880+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 653 for task copy_files_to_hadoop (sh summa.sh; 57701)
[2024-01-02T23:25:35.899+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T23:25:35.913+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
