[2023-12-09T16:06:29.463+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:36:23.119204+00:00 [queued]>
[2023-12-09T16:06:29.478+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:36:23.119204+00:00 [queued]>
[2023-12-09T16:06:29.478+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T16:06:29.489+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-12-09 10:36:23.119204+00:00
[2023-12-09T16:06:29.495+0530] {standard_task_runner.py:57} INFO - Started process 18130 to run task
[2023-12-09T16:06:29.498+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Cricbuzz_ETL', 'load', 'manual__2023-12-09T10:36:23.119204+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/Crickbuzz_dag.py', '--cfg-path', '/tmp/tmpb_q4ks9c']
[2023-12-09T16:06:29.499+0530] {standard_task_runner.py:85} INFO - Job 140: Subtask load
[2023-12-09T16:06:29.547+0530] {task_command.py:416} INFO - Running <TaskInstance: Cricbuzz_ETL.load manual__2023-12-09T10:36:23.119204+00:00 [running]> on host Iris
[2023-12-09T16:06:29.609+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Cricbuzz_ETL' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T10:36:23.119204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T10:36:23.119204+00:00'
[2023-12-09T16:06:29.630+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2023-12-09T16:06:29.635+0530] {logging_mixin.py:154} INFO - bala
[2023-12-09T16:06:29.635+0530] {logging_mixin.py:154} INFO - 

---------------------------<connection object at 0x7f533dd86e00; dsn: 'user=postgres password=xxx dbname=postgres host=localhost port=5432', closed: 0> --------------------------------
[2023-12-09T16:06:29.637+0530] {base.py:73} INFO - Using connection ID 'Cricbuzz_db' for task execution.
[2023-12-09T16:06:29.638+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/rajabala/Desktop/projects/Airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/rajabala/Desktop/projects/Airflow/dags/Cricbuzz_files/Load.py", line 40, in load_to_db
    f'postgresql+psycopg2://{conn.user}:{conn.password}@{conn.host}:{conn.port}/{conn.dbname}'
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'user'
[2023-12-09T16:06:29.641+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Cricbuzz_ETL, task_id=load, execution_date=20231209T103623, start_date=20231209T103629, end_date=20231209T103629
[2023-12-09T16:06:29.652+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task load ('psycopg2.extensions.connection' object has no attribute 'user'; 18130)
[2023-12-09T16:06:29.676+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T16:06:29.686+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
